### ISSUE TITLE
`db.add` causes AttributeError: 'BatchClientStorage' object has no attribute 'db'

### ISSUE THREAD

**Issue by jean** [zerodb/zerodb#46]
Following the docs at https://docs.zerodb.com/#using-zerodb-in-python

```
In [8]: db.add(e)
ERROR:ZEO.zrpc.Connection('C'):(127.0.0.1:8001) invalidateTransaction() raised exception: 'BatchClientStorage' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/zrpc/connection.py", line 476, in handle_request
    ret = meth(*args)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/ClientStorage.py", line 1469, in invalidateTransaction
    self._process_invalidations(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zerodb/storage/batch.py", line 41, in _process_invalidations
    self._db.invalidate(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 116, in invalidate
    return self.db.invalidate(transaction_id, oids, version)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 53, in __getattr__
    return getattr(self.base, name)
AttributeError: 'BatchClientStorage' object has no attribute 'db'
ERROR:ZEO.zrpc.Connection('C'):(127.0.0.1:8001) Asynchronous call raised exception: <ManagedClientConnection ('127.0.0.1', 8001)>
Traceback (most recent call last):
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/zrpc/connection.py", line 476, in handle_request
    ret = meth(*args)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/ClientStorage.py", line 1469, in invalidateTransaction
    self._process_invalidations(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zerodb/storage/batch.py", line 41, in _process_invalidations
    self._db.invalidate(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 116, in invalidate
    return self.db.invalidate(transaction_id, oids, version)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 53, in __getattr__
    return getattr(self.base, name)
AttributeError: 'BatchClientStorage' object has no attribute 'db'
Out[8]: 625566997
```

**Comment by michwill** [comment]
Strange as well, also cannot reproduce as well.

Can you post exact steps how you installed virtual environment to get it, what OS do you have, etc?

**Comment by michwill** [comment]
So, if you turn debug on, healthy messages should look like:
```
In [9]: logging.basicConfig(level=logging.DEBUG)

In [10]: e = models.Employee(name="John", surname="Smith", salary=150000,description="Coding power")
    ...: 

In [11]: db.add(e)
    ...: 
DEBUG:txn.140273990907712:new transaction
Out[11]: 841792871
```

**Comment by jean** [comment]
Here's a lightly edited session:

```
13:27 john@X250:~/git$ git clone git@github.com:zerodb/zerodb-server.git
13:28 john@X250:~/git$ cd zerodb-server
13:28 john@X250:~/git/zerodb-server(master)$ virtualenv venv
13:29 john@X250:~/git/zerodb-server(master)$ . venv/bin/activate
(venv)13:29 john@X250:~/git/zerodb-server(master)$ cd demo/
(venv)13:29 john@X250:~/git/zerodb-server/demo(master)$ pip install -r requirements.txt
(venv)13:30 john@X250:~/git/zerodb-server/demo(master)$ zerodb-manage init_db
(venv)13:31 john@X250:~/git/zerodb-server/demo(master)$ zerodb-server &
(venv)13:31 john@X250:~/git/zerodb-server/demo(master)$ zerodb-manage console
In [1]: pubkey = get_pubkey('john', 'password')
In [2]: useradd('john', pubkey)
In [3]: import models
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zerodbext/server/manage.pyc in <module>()
----> 1 import models  
ImportError: No module named models
In [4]: import sys
In [5]: sys.path.append('.')
In [6]: import models
In [7]: import transaction
In [8]: import zerodb
In [9]: db = zerodb.DB(("localhost", 8001), username="root", password="root")
2016-07-14T13:33:13 INFO ZEO.zrpc.Connection('S') (127.0.0.1:55774) received handshake 'Z4'
ERROR:ZEO.zrpc.Connection('C'):(127.0.0.1:8001) invalidateTransaction() raised exception: 'BatchClientStorage' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/zrpc/connection.py", line 476, in handle_request
    ret = meth(*args)  
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/ZEO/ClientStorage.py", line 1469, in invalidateTransaction
    self._process_invalidations(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zerodb/storage/batch.py", line 41, in _process_invalidations
    self._db.invalidate(tid, oids)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 116, in invalidate
    return self.db.invalidate(transaction_id, oids, version)
  File "/home/john/repos/git/zerodb-server/venv/local/lib/python2.7/site-packages/zc/zlibstorage/__init__.py", line 53, in __getattr__
    return getattr(self.base, name)
AttributeError: 'BatchClientStorage' object has no attribute 'db'
In [10]: db
Out[10]: <zerodb.db.DB at 0x7f935c1986d0>
```

System:    Host: X250 Kernel: 3.19.0-32-generic x86_64 (64 bit)
           Desktop: Cinnamon 2.8.8  Distro: Linux Mint 17.3 Rosa

Here's a terminalcast of the above session: https://asciinema.org/a/bt4bm0yw8h06ya876rlthp7xg

I notice your `virtualenv.sh` does a few things I normally don't.

**Comment by jean** [comment]
I notice the docs state: 

> Navigate to the `demo` directory and install the necessary packages:

(.i.e. use `zerodb-server/demo/requirements.txt`) but `zerodb-server/virtualenv.sh` uses `zerodb-server/requirements.txt`

**Comment by michwill** [comment]
Re: docs - yes. docs imply demo/requirements.txt, but you can use either. The only difference is that virtualenv.sh will use zerodb-server from git while requirements.txt use pypi.

**Comment by michwill** [comment]
Thanks for the screencast. Interesting thing I've noticed is that you use management terminal to run a demo. The demo is assumed to run separately. For example, you can start zerodb-server and then use python create.py, or run a fresh new ipython terminal in demo/ directory.

But let me check if your observation is caused by this..

**Comment by michwill** [comment]
Indeed, this appears only in "zerodb-manage console". If you run a separate ipython terminal (how it is supposed to be), no errors observed (even when DEBUG logging level is set).

**Comment by michwill** [comment]
Ok, apparently fixed both (check out the new version of zerodb-server!). So, root can do queries in the console and you can import models (or whatever in current directory).

The only thing which will not work now is if you will connect under a new (non-root) user from inside management console while being connected as root. This I will fix after we start using ZEO5 (shortly)
